var methods_url = "https://github.com/litwr2/research-of-sorting/blob/master/"
var json_methods = '{\
"array*1": "array.cpp",\
"array*2": "array.cpp",\
"array*3": "array.cpp",\
"array*5": "array.cpp",\
"array*7": "array.cpp",\
"bubble": "bubble.cpp",\
"clib_qsort": "std.cpp",\
"combo": "combo.cpp",\
"flat_stable": "boost.cpp",\
"hash": "hash.cpp",\
"hashbt": "hashtree.cpp",\
"hashbt_boost": "hashtree.cpp",\
"hashbt_std": "hashtree.cpp",\
"heapsort_bsd": "bsd.cpp",\
"heapsort_stl": "std.cpp",\
"insertion": "insertion.cpp",\
"mergesort_bsd": "bsd.cpp",\
"pdq": "boost.cpp",\
"qsort_dualpivot": "quick-dp.cpp",\
"qsort_hoare": "quick-hoare.cpp",\
"qsort_hoare2": "quick-hoare.cpp",\
"qsort_hoare_tco": "quick-hoare.cpp",\
"qsort_lomuto": "quick-lomuto.cpp",\
"qsort_no_pivot": "quick-np.cpp",\
"qsort_safe": "quick-safe-insertion.cpp",\
"qsort_safe_nss": "quick-safe-insertion-nss.cpp",\
"radix11": "radix.cpp",\
"radix11_msd": "radix-msd.cpp",\
"radix16": "radix.cpp",\
"radix16_msd": "radix-msd.cpp",\
"radix8": "radix.cpp",\
"radix8_msd": "radix-msd.cpp",\
"radix8_msd_oms7": "oms7.cpp",\
"radix8_oms7": "oms7.cpp",\
"radix8_trie": "trie.cpp",\
"radix_bsd": "bsd.cpp",\
"selection": "selection.cpp",\
"shell_10/3": "shell-tab.cpp",\
"shell_10/3_oms7": "oms7.cpp",\
"shell_2.25": "shell-tab.cpp",\
"shell_a102549": "shell-tab.cpp",\
"shell_a102549m": "shell-tab.cpp",\
"shell_a3n": "shell-plain.cpp",\
"shell_prime_10/3": "shell-tab.cpp",\
"shell_prime_2": "shell-tab.cpp",\
"shell_prime_e": "shell-tab.cpp",\
"spin": "boost.cpp",\
"spread": "boost.cpp",\
"sradix_bsd": "bsd.cpp",\
"stlsort": "std.cpp",\
"stlstable": "std.cpp",\
"timsort": "tim.cpp",\
"tree_boost": "tree.cpp",\
"tree_stl": "tree.cpp"}'

